### ISSUE TITLE
Sync error under Windows

### ISSUE THREAD

**Issue by graphixillusion** [volllly/rotz#329]
Hi there. As the title says i'm getting this error when i try to run the sync command under Windows.

Error: glob::set::parse

  x Could not build GlobSet
  `-> failed to parse glob expression

I don't know if i'm doing something wrong but i just initialize rotz with `rotz init,` then add things into the .dotfiles folder and then i've tried the sync command and got this error.

**Comment by t-mart** [comment]
+1 to this. Happy to explain more if questions are asked.

In fact, I'm not really sure what this command is supposed to do... Aren't the deployed dotfiles already linked to the respective file in `.dotfiles`?

**Comment by t-mart** [comment]
Ah, ok. When I specified a specific dot (e.g., `rotz sync aria2`), it tried to push _something_ to the origin. However, because I'd already manually `git push`-ed, the command failed. In other words, rotz was not able to detect that the branch was up-to-date with the origin and gave a non-zero exit code.

If it helps, I just converted my dotfiles repo to rotz at <https://github.com/t-mart/dotfiles>.

FWIW, this subcommand feels a bit "extra", if it is just a wrapper around `git push`. It's implied that users are already working with git because `rotz clone`, the "entrypoint" to rotz, requires an existing repo. Therefore, maybe they could manage these steps with git directly and get full control.

Additionally, it opens up a ton of surface area in understanding the state of a git repository.

- How does it handle uncommitted work?
- What if I'm not on the `master` branch?
- What if it's called `main` instead?
- As stated before, could it better detect if the branch is already up-to-date with the upstream?

I'd like to know more about your philosophy on this one, @volllly.

**Comment by volllly** [comment]
Hey @graphixillusion, the current version has a bug leading to this problem. I'll fix it in a new release soon.

**Comment by volllly** [comment]
Hey, @t-mart,

I agree with you that the `sync` command is bloat/bad/not worth the effort.
It's something added because I could but without a real need for it 😅 (I tend to do that)

Ideally I'd like the `init` and `clone` commands to [use the `gitoxide` or `git2` crates](https://github.com/volllly/rotz/issues/143) (but I'm struggling with getting that working) so you can clone your dotfiles without having git installed and then use rotz to `rotz install` git.

I've started a poll to get some more feedback on the sync command 😁 Thanks for your input
https://github.com/volllly/rotz/discussions/334
